### ISSUE TITLE
Pink video

### ISSUE THREAD

**Issue by yeahme49** [themactep/thingino-firmware#106]
I flashed a Wyze V3 with the latest Thingino and I get pink hues on the video. I saw there was a commit yesterday (https://github.com/themactep/thingino-firmware/commit/b88cb7262dd3667e816868cdd624a1362045fb6a) that changed the order of the ircut pins. I actually had to swap it back to 
gpio_ircut=52 53
to get the image to look correct. I'm not sure if some Wyze V3 have them backwards or what.

**Comment by gtxaspec** [comment]
thanks for the report, fixed in https://github.com/themactep/thingino-firmware/commit/8d17117c31b9889635cbc7b7451501253007a68f
