### ISSUE TITLE
gpio_speaker needs active high/low configuration

### ISSUE THREAD

**Issue by jayfan0** [themactep/thingino-firmware#113]
current env variable `gpio_speaker` seems to either be disabled or active high with the audio module.

current `/etc/modules.d/audio` is
```
audio spk_gpio=$(fw_printenv -n gpio_speaker || echo -1)
```

need to add logic with either `o` or `O` with the `gpio-speaker` definition to make the parameter as follows:

```
audio spk_gpio=$(fw_printenv -n gpio_speaker || echo -1) spk_level=0
```
where:
```
-1 = disabled
0 = active low
1 = active high
```

**Comment by gtxaspec** [comment]
fixed in https://github.com/themactep/thingino-firmware/commit/35ad8bf0bbccbada43a75666bebecbb1e0829f08

**Comment by jayfan0** [comment]
Thank you for this.

I can confirm that it works.

Both functionally and electrically (with a meter on the amplifier enable pin) for my camera, pin 63 is correctly set on kernel boot:

gpio_speaker 63 = amplifier is set high (3.3v)
gpio_speaker 63O = amplifier is set high (3.3v)
gpio_speaker 63o = amplifier is set low (0v)

**Comment by jayfan0** [comment]
update: 

Not defining any pin in gpio_speaker does not automatically set to `-1`. 
Defaults to 63 active high

**Comment by gtxaspec** [comment]
fixed in https://github.com/themactep/thingino-firmware/commit/d805d5495dcea30e2d784d35c7b535eae40b631b

default is set to -1 if no gpio is specified in ENV

**Comment by jayfan0** [comment]
tested and works fine. thank you

gpio_speaker 63 = amplifier is set high (3.3v)
gpio_speaker 63O = amplifier is set high (3.3v)
gpio_speaker 63o = amplifier is set low (0v)
gpio_speaker <undefined> = gpio 63 is free to manually toggle
