### ISSUE TITLE
Feature request -  Add Homekit integration via go2rtc

### ISSUE THREAD

**Issue by theBr3ach** [themactep/thingino-firmware#162]
https://github.com/OpenIPC/wiki/blob/52fc69bb9394d0581e6589d3726d34815a6301bb/en/homekit-integration.md?plain=1#L3

**Comment by gtxaspec** [comment]
go2rtc is already included as a package, though it is the mini version.  I'll update the package to include the full one that includes homekit stuff.  stay tuned.

`BR2_PACKAGE_GO2RTC=y`

**Comment by gtxaspec** [comment]
will need some buildroot updates to make this work, currently host-go does not compile with the version of buildroot we are using.

**Comment by gtxaspec** [comment]
buildroot was updated, i'll test go2rtc shortly.

**Comment by gtxaspec** [comment]
enabling `BR2_PACKAGE_GO2RTC=y` in your build will successfully build go2rtc now.
