### ISSUE TITLE
SD card format in GUI only formats the existing partition ignoring the rest of the space

### ISSUE THREAD

**Issue by invisible999** [themactep/thingino-firmware#177]
If SD card has a partition that occupies only part of the space, Thinkgino's 'Format SD card' feature in menu tools->sd card only formats the existing partition with FAT32 and ignores the rest of the space.

The formatter should check the total size of the sd card and if formatting it should use all available space and have an option to select FAT32 or exFAT.

**Comment by themactep** [comment]
please test if the issue still persists with the new formatter.
