### ISSUE TITLE
[feature] Add custom additionnal time for day/night option

### ISSUE THREAD

**Issue by Sigri44** [themactep/thingino-firmware#191]
Hey, for "Dusk to Dawn", can we obtain two new field ?

- "diff to day", and
- "diff to night"

Because value has not good for my installation, and think can alterate official time, can be more customisable 🙂
Like "+ 1 h 15 min"

Ex : 
My auto time set day at 7 AM, but sun is here at 8:15 AM, so picture still stuck :

<img width="878" alt="image" src="https://github.com/user-attachments/assets/4e6afbbb-68ae-4325-930e-99eafaca139c">

<img width="879" alt="image" src="https://github.com/user-attachments/assets/46dc14e2-491d-4ce5-8306-c7d644c9bee2">

<img width="878" alt="image" src="https://github.com/user-attachments/assets/ea538f5d-c4cb-4e29-8698-d73cd3c00f4f">

**Comment by themactep** [comment]
https://github.com/themactep/thingino-firmware/commit/67ae80ab7b6cf82885844c51cc33bace400081a7
please test it out and let me know if any issues.

**Comment by Sigri44** [comment]
> [67ae80a](https://github.com/themactep/thingino-firmware/commit/67ae80ab7b6cf82885844c51cc33bace400081a7) please test it out and let me know if any issues.

Done, but don't know hot to test it

<img width="753" alt="image" src="https://github.com/user-attachments/assets/26d4fc70-f140-4651-858a-2b7d16a4ad33">

<img width="291" alt="image" src="https://github.com/user-attachments/assets/ef83766b-d074-4757-963c-221167ad91c4">

<img width="840" alt="image" src="https://github.com/user-attachments/assets/977e759d-b947-47c0-a73d-2ed57b24e090">

**Comment by themactep** [comment]
just upgrade the image, all changes are already there.

**Comment by themactep** [comment]
please reopen if you have issues with the updated script.
