### ISSUE TITLE
webui - display hostname in title

### ISSUE THREAD

**Issue by gtxaspec** [themactep/thingino-firmware#197]
**Problem:**
Currently, all browser tab titles are identical across multiple hosts, making it difficult to distinguish between different windows or tabs when working with multiple hosts simultaneously.

**Proposed Solution:**
To improve usability, the hostname should be included in the browser tab titles.  This would make it easier to quickly identify and switch between different hosts.

**Example:**
See attached screenshot for examples.

![image](https://github.com/user-attachments/assets/0303297e-b36d-49dc-a6fb-55a5199ac401)

**Comment by themactep** [comment]
done.
