### ISSUE TITLE
Starting wireless

### ISSUE THREAD

**Issue by spstrademark** [themactep/thingino-firmware#200]
Hello,

i am using the T31L processor with 8 MB flash and cinnado d1.
Got the precompiled bin _thingino-cinnado_d1_t31l.bin_ from here :

[](https://github.com/themactep/thingino-firmware/releases/tag/firmware)
After flashing the bin i get a message " Starting wireless " and the device stops working there.
I have attached a screenshot with the recieved message.
Thank you for your response!

Best regards,
Stanko
![starting_wireless](https://github.com/user-attachments/assets/136150e0-fb1b-4551-9580-3f82aff102f6)

**Comment by gtxaspec** [comment]
@spstrademark wrong image, you are using the cinnado firmware for the t23 soc, check the file name.  
you need the T31 image.

**Comment by themactep** [comment]
How did you set up the wireless access? From shell over uart or from camera access point and the portal?

**Comment by spstrademark** [comment]
Hello,

both ways do not work. The portal doesn't show up. Through the shell, settings can be made, but the camera does not connect to router.
Thank you for your time.

**Comment by yangminglong** [comment]
> Hello,
> 
> both ways do not work. The portal doesn't show up. Through the shell, settings can be made, but the camera does not connect to router. Thank you for your time.

Can you provide more information

**Comment by wltechblog** [comment]
Does the interface show up when you run iwconfig?

**Comment by themactep** [comment]
need more info

**Comment by spstrademark** [comment]
Hello,

i have attached the log from the camera
[firstboot.txt](https://github.com/user-attachments/files/17144460/firstboot.txt)

![1](https://github.com/user-attachments/assets/a0eac235-5813-473b-ba70-a6c21a4c6a91)
![2](https://github.com/user-attachments/assets/cffc1bdf-996b-40f0-97e0-1c792793719f)
![3](https://github.com/user-attachments/assets/d2aed41e-0019-47ef-b83a-01457c5fee2a)

and screenshots what i am recieving 

Thank you for your time!

**Comment by themactep** [comment]
Please download a fresh firmware build for your camera, save it on an sd card as `autoupdate-full.bin`, insert it into the camera and reboot with it. Three weeks old build is not something worth investigating. Most likely the error was fixed while ago. If you still have that error after upgrade, then we will start testing it.

**Comment by spstrademark** [comment]
Hi, 

the problem persists. But now when trying to connect to wireless there is a blue led blinking. I am flashing the firmware with the usb cloner and it gets stuck on starting wireless.
iwconfig is saying there is no such interface loaded.
![Screenshot_1](https://github.com/user-attachments/assets/866d8d6e-1e99-4b21-a951-7c6e8fd0c5f6)

modprobe -l returns atbm6031.ko
[20240930-thingino-log.txt](https://github.com/user-attachments/files/17199605/20240930-thingino-log.txt)
[20240930-thingino-log-failsafe.txt](https://github.com/user-attachments/files/17199606/20240930-thingino-log-failsafe.txt)
[20240930-thingino-log-firstboot.txt](https://github.com/user-attachments/files/17199607/20240930-thingino-log-firstboot.txt)

Thank you for your time!

**Comment by gtxaspec** [comment]
please run `thingino-diag -l` and attach the logs

**Comment by spstrademark** [comment]
Hello,

i have attached the log file.

Thank you for your time!

[20241002-thingino-diag-log.txt](https://github.com/user-attachments/files/17219689/20241002-thingino-diag-log.txt)
