### ISSUE TITLE
extensive table of hardware

### ISSUE THREAD

**Issue by ouinouin** [themactep/thingino-firmware#211]
Hi, just went through this amazing project, as being a fan of openwrt on routers, i see this software as the openwrt for cameras.
i m seeking for a camera with RJ45 and POE, and went through the list without finding it.
Indeed, i feel like for openwrt, a table of hardware with characteristics of each camera would be great to choose supported hardware in a blink (yes, i know, the version of hardware and so are complicated to get).  at least having a list with functionalties like : 
sensor size| wifi | ethernet | POE | PTZ function |sdcard function.

this issue could be a start to consolidate a list of characteristics of each camera?

**Comment by themactep** [comment]
Here you go. https://dariuskt.github.io/thingino-toh/
