### ISSUE TITLE
T31X GC4653 ethernet

### ISSUE THREAD

**Issue by kaar3l** [themactep/thingino-firmware#217]
Hello I did buy 4 cameras with T31 + GC4653. I removed flash chip and installed thingino-vanhua_z55i.bin firmware. First 2 cameras were perfect, after flashing booted up and ethernet was working like charm. Next two cameras I flashed with exactly the same firmware and nothing. The ethernet doesn't work. The boards seem identical.

These are the 2 cameras that are not working:
![IMG_20240925_124544](https://github.com/user-attachments/assets/be60a6f1-6a31-4145-a4b3-325affbf55b7)
![IMG_20240925_124537](https://github.com/user-attachments/assets/7a3390ad-bda7-459f-9790-6d60d7877846)

I did solder serial to the cameras and seems that the cameras boot up but no ethernet connection is made.

What could I try to start the ethernet?

**Comment by gtxaspec** [comment]
can you take a photo of the bottom of the board?

**Comment by kaar3l** [comment]
Not the best quality but here it is.
![1727263600616](https://github.com/user-attachments/assets/4e54c4dd-83b6-4489-9905-aff8c2c580c8)
I did not compare the other side of the camera board with the working one.

**Comment by themactep** [comment]
these modules are better flashed over serial port. login to uboot, use ymodem to upload the image. it takes time but it's safer than removing the flash chip. try to flash stock back and confirm that ethernet works. if it does not - the module is damaged during soldering. phy chip is located on the opposite side of the flash chip, between two uarts.

**Comment by themactep** [comment]
![IMG_20240925_133207.jpg](https://github.com/user-attachments/assets/5d9fafd6-c23b-4242-a7c9-0d52c7f07c3b)

This one is on my bench right now. Ethernet works with thingino ootb.

**Comment by themactep** [comment]
please feel free to reopen if you find a confirmation that the issue is in the firmware.
