### ISSUE TITLE
Xiaomi iSC5 sound issues

### ISSUE THREAD

**Issue by tERB00** [themactep/thingino-firmware#219]
First of all thank you to all Thingino devs for your hard work!

I just installed the firmware on my old Xiaomi iSC5 and it works fine out of the box except few small things.

One of them is audio. Audio playback works but it plays audio very fast (probably compile error).
But the audio input (mic) does not work at all. I can see audio track on the rtsp stream, changing the codec changes the stream's audio codec too but there is no audio. Complete silence. No hiss, no humm - nothing. Enabling AGC does not affect anything as well.

I would like to help in debugging that.

**Comment by tERB00** [comment]
My bad - no mic was a VLC issue, sorry about that.
Fast playback is still an issue tho.

**Comment by themactep** [comment]
make sure you have speaker gpio pin defined and it is set to power up the amplifier ic.

**Comment by tERB00** [comment]
I didn't compiled the firmware but there is
_gpio_speaker=63_
in uenv

**Comment by gtxaspec** [comment]
does fast playback happen in other players, or just VLC? try MPV/go2rtc/etc to test.

**Comment by tERB00** [comment]
Oh. Fast playback is in the camera's speaker, not in the player
