### ISSUE TITLE
how to determine which Wyzecam V3 variant you have

### ISSUE THREAD

**Issue by goatzillax** [themactep/thingino-firmware#231]
I'm still running wz_mini_hacks but I think I'm kind of ready to jump ship as of the recent forced update.

How do I figure out which of the 5 apparent variants my V3 is?

lsmod shows:

```
sensor_gc2053_t31 11314 0 - Live 0xc0844000 (O)
8189fs 1601252 0 - Live 0xc05f0000 (O)
```

That seems to narrow it down to two, however what's the difference between T31X and T31ZX?  Does the difference show up in dmesg or cpuinfo?

Is it possible to figure it out without cracking the camera open?

**Comment by tERB00** [comment]
You have to backup your original firmware anyways before doing anything else. So try out and see if Ingenic USB Cloner works. If not you have to open it and hook up UART.

**Comment by gtxaspec** [comment]
z and zx are interchangeable, the big difference is T31A or Z/ZX.  run this command in the shell and share the output:
`devmem 0x13540238`

**Comment by goatzillax** [comment]
OK great.  The raw devmem gave:

```
# devmem 0x13540238
0x66661111
```

And that script returned: 

```
t31zx
```

So it seems the firmware I want is "T31ZX, GC2053, RTL8189FTV, 16MB".  Any other low-hanging fruit I should look at?

Thanks!

**Comment by themactep** [comment]
I advise joining our [Telegram group](https://t.me/thingino) and [Discord server](https://discord.gg/BTrPtSEN) for support questions. Please leave GH Issues for issues. Thank you.
