### ISSUE TITLE
Bricked Wyze Cam V2 while flashing

### ISSUE THREAD

**Issue by Vendo233** [themactep/thingino-firmware#232]
my cam is dead, no LED, what can I do. Are there points on the board to flash it via serial?

**Comment by themactep** [comment]
I advise reading [wiki](https://github.com/themactep/thingino-firmware/wiki) and joining our [Telegram group](https://t.me/thingino) and [Discord server](https://discord.gg/BTrPtSEN) for support questions. Please leave GH Issues for issues. Thank you.
