### ISSUE TITLE
Feature: Permanent wifi AP mode for uses without existing wifi

### ISSUE THREAD

**Issue by wltechblog** [themactep/thingino-firmware#262]
This would allow cameras to be more easily used in locations with power but without existing wifi connectivity, and would only be a slight tweak to the captive portal setup

**Comment by tavicu** [comment]
That would be very cool.

I always thought about this when I went camping with my tent. It would be cool to be able to power the camera from an external battery and be able to see on your phone outside the tent.

**Comment by gtxaspec** [comment]
added in https://github.com/themactep/thingino-firmware/commit/88e6e3b13ca2899afd53fb454923dad618ef8176

**Comment by themactep** [comment]
please test in the fresh builds and confirm it works for you.

**Comment by themactep** [comment]
It works.
