### ISSUE TITLE
BUG: Initial setup portal page appears even when usb0 is connected/configured and wifi credentials removed

### ISSUE THREAD

**Issue by clee604** [themactep/thingino-firmware#273]
As part of long discussion item here: https://github.com/themactep/thingino-firmware/discussions/213

`so we currently check for eth0, and if present, the portal is disabled... we should probably extend this to usb0`

It also blocks me from entering any of the settings pages (they 404) via direct URLs.

![image](https://github.com/user-attachments/assets/1a502ed1-1d85-47d3-8618-5ed97b0490b5)

To reproduce:
1. Set up camera to use usb0 as main interface via usb-ncm
2. Once confirmed working, disable wifi by wiping wifi ssid and password 
3. Reboot, and the portal page comes up

**Comment by gtxaspec** [comment]
fixed in https://github.com/themactep/thingino-firmware/commit/bf4445d850c90ca3104af25a0c220cfb63de19c4
