### ISSUE TITLE
Changing wireless network options saves to wireguard interface instead.

### ISSUE THREAD

**Issue by tERB00** [themactep/thingino-firmware#275]
Whenever you change network settings on the config-network.cgi page for the wlan0 interface it saves to wg0 instead.
Clearly there is not enough grepping but haserl scripting is too evil for me to understand and I cant find where exactly is the mistake, sorry.

**Comment by ckuethe** [comment]
Hm. I'll have a look at this since the wireguard config page was my creation

**Comment by themactep** [comment]
please add relevant info from /tmp/webui.log

**Comment by tERB00** [comment]
wg0 before:
```
auto wg0
iface wg0 inet static
    # WireGuard
    # +static
    pre-up modprobe wireguard
    pre-up ip link add dev wg0 type wireguard
    pre-up wg setconf wg0 /etc/wireguard.conf
    post-down ip link del dev wg0
```

Web Ui Log:
```
setnetiface -i wg0 -m static -h "xiaofang" -a 10.10.10.45 -n 255.255.255.0 -g 10.10.10.1 -d 10.10.10.1
2024-10-27 06:05:43 [14844:network] Plugin network initialized
2024-10-27 06:05:43 [14844:network] Configuration file /etc/webui/network.conf not found
2024-10-27 06:05:43 [14844:network] Exit with code 0.
```

wg0 after:
```
auto wg0
iface wg0 inet static
    address 10.10.10.45
    netmask 255.255.255.0
    gateway 10.10.10.1
    pre-up echo -e "nameserver 10.10.10.1\n" >/tmp/resolv.conf
    # WireGuard
    # +static
    pre-up modprobe wireguard
    pre-up ip link add dev wg0 type wireguard
    pre-up wg setconf wg0 /etc/wireguard.conf
    post-down ip link del dev wg0
```

**Comment by themactep** [comment]
Script runs changes explicitly for wg0. Can you please make a screenshot of the form before you submit? What interface is selected?

**Comment by tERB00** [comment]
I'm doing this in the Network Settings menu. There are 2 network interfaces in the list - eth0 (even tho xiaofang does not have any ethernet ports) and wlan0. Wlan0 is selected when I am making changes.
![image](https://github.com/user-attachments/assets/1228741c-a829-45ef-9e05-ea9c3a39032c)

**Comment by themactep** [comment]
do you use wireguard? or is it just picked up randomly?

**Comment by tERB00** [comment]
Yeah I use wireguard and no it does not break it adding these lines to the wg0 interface config.

**Comment by themactep** [comment]
no, the reason i asked is because the interface settings were taken from default interface which seems in your case was wg0. i changed the form to use explicitly the interface submitted from the form. please pull and test.

**Comment by tERB00** [comment]
Well it does not change wg0 anymore which is good. It reverts to dhcp no matter what tho.
But it is an another issue https://github.com/themactep/thingino-firmware/issues/254
Thanks Paul!
