### ISSUE TITLE
bug: changing fps in the gui doesn't do anything

### ISSUE THREAD

**Issue by nicolasroche898** [themactep/thingino-firmware#284]
repro:
flash a new jooan camera
observe "25fps" in the streamer config page
move the "fps" scroll bar to 15fps with the mouse. 
web ui shows 15 fps... but settings are NOT saved anywhere:

seen: cat /etc/prudynt.cfg still shows 25fps
expected: cat /etc/prudynt.cfg should show 15fps

note: manually editing the config file vi /etc/prudynt.cfg to 15fps fixes the problem

**Comment by themactep** [comment]
Open console in browser dev tools (f12) and check request and response from prudunt in console log. Do you get any error?

**Comment by nicolasroche898** [comment]
changing from 15fps to 14fps in the gui:

```
1729924404270 '===>' '{"stream0":{"fps":14},"action":{"save_config":null,"restart_thread":3}}'
config-streamer.cgi:697
1729924404334 '<===' '{"stream0":{"fps":14},"action":{"save_config":"initiated","restart_thread":"initiated"}}'
```

**Comment by nicolasroche898** [comment]
waitasec, now in config file:
fps = 14;

so problems exists only in initial configuration?
i'll reset the camera and try again

**Comment by nicolasroche898** [comment]
well that it very weird. now modification works from web gui. i don't know what to say.

**Comment by nicolasroche898** [comment]
keep it open, if i can't reproduce in the next few days, i'll close

**Comment by nicolasroche898** [comment]
tested again on new camera. couldn't reproduce. closing.
