### ISSUE TITLE
pwm-ctrl miss a read duty cycle option.

### ISSUE THREAD

**Issue by bonjour81** [themactep/thingino-firmware#293]
Hello,

As far as I understood, pwm-ctrl offers 2 functions:
- list available pwm channels
- set pwm duty cycle of a channel (with or without reverse polarity)

Would it be possible to add a read command ? 

I currently did not date using set pwm as I’m not sure what is current / default value.

**Comment by bonjour81** [comment]
Hello,  yes I have seen pwm command but I was not able to figure out the link between pwm  channel (0‐3) and IR led pin 47/49  (on wyze v3)

**Comment by gtxaspec** [comment]
added read function:
https://github.com/themactep/thingino-firmware/commit/d8caa5a8559c14cdb56a86f0920eb997e18e5db3
