### ISSUE TITLE
Preview does not load through reverse proxy

### ISSUE THREAD

**Issue by timkeefer1** [themactep/thingino-firmware#295]
I'm running nginx proxy manager and passing the web admin interface (using SSL/CF tunnel).  The Preview image is not loading - I think the webui page is trying to use the RTSP feed, rather than the MJPEG feed.  From the client, nothing loads on the web side, and in the console it looks like the div "row preview" - "col-lg-9 mb-3" - "small" is calling "playrtsp"  

Maybe the default preview pane should be pulling the MJPEG feed instead (/x/mjpeg.cgi)?  Or maybe it could be selectable on the Preview pane?

**Comment by gtxaspec** [comment]
can you share the full log from the browser developer console?

**Comment by nicolasroche898** [comment]
same issue as #296 preview is initiated via websocket on port 8089. you need to pass this port/websocket via your proxy too.

**Comment by timkeefer1** [comment]
Thanks for the help on this!  Now I just need to figure out how to do that through NPM, since my nginx skills are bleh.

**Comment by themactep** [comment]
fixed. please test and confirm.
