### ISSUE TITLE
bug: webui: reset firmware doesn't work

### ISSUE THREAD

**Issue by nicolasroche898** [themactep/thingino-firmware#300]
repro:
in web ui go to: settings -> reset, click button: "reset firmware" + Yes

expected:
firmware is reset.

actual:
this is printed for 1 second on the web page, then goes to "restarting" page, but camera is not restarted and continues as normal (not reset)...

```
[@ing-jooan-a6m-654a /tmp]# firstboot

!!! Warning !!!

This action will reset the device to defaults and erase all configurations, leaving the device like the first boot.

All saved settings will be erased!

Are you sure you want to proceed? (yes/no)
Operation aborted.

EXIT CODE: 1

```

**Comment by themactep** [comment]
please test with the new build and see it it works now

**Comment by nicolasroche898** [comment]
new test on:
BUILD_ID="master+a4ca4b2, 2024-11-04 09:36:06 -0500"

steps:
wipe flash and install new firmware
change and save any setting
go to: settings -> reset -> reset firmware -> Yes

result:
camera is reset to original state correctly and transmitting THINGINO AP.
bug fixed.

web browser stays in this state:
i guess there isn't much that can be done about that, as camera won't be accessible anymore after reset.

![reset_firmware](https://github.com/user-attachments/assets/84e5fd2f-e427-4e7d-9372-102bb9d53cd7)

**Comment by themactep** [comment]
i replaced the buttons with a link to a wiki article about camera configuration.

**Comment by themactep** [comment]
fixed.
