### ISSUE TITLE
use protocol-relative websocket on all cgi pages

### ISSUE THREAD

**Issue by nicolasroche898** [themactep/thingino-firmware#302]
in all cgi pages, replace all `WebSocket('ws://' +` with `WebSocket('//' +`

this approach will make the browser automatically use wss:// if the page is loaded over HTTPS and ws:// if the page is loaded over HTTP, without the need for any rewrite rules for https proxy.

related #296 
[see comment](https://github.com/themactep/thingino-firmware/issues/296#issuecomment-2452989238)

**Comment by themactep** [comment]
done. please test and confirm it's solved.

**Comment by nicolasroche898** [comment]
tested, confirmed solved.

**Comment by jspiros** [comment]
FYI, this change broke the Thingino web interface for users of Firefox ESR 115.x, as support for WebSocket URLs that lack the protocol component wasn't added until Firefox 124 (https://bugzilla.mozilla.org/show_bug.cgi?id=1797449). Under Firefox 115.x, the changed lines cause a DOMException and the page is non-functional. As of now, ESR 115 remains the supported version of Firefox for Windows 7-8.1 and macOS 10.12-10.14.

> For folks affected by the change in browser behavior, here's the status as of today (2024-05-10):
> 
> 
> 
> - Firefox shipped in 124.0 (released 2024-03-19)
> 
> - Safari shipped this in 17 a.k.a. 19616.1.27 (released 2023-09-18)
> 
> - Chromium shipped this in 125 (released 2024-05-08)
> 
>   - ticket: https://issues.chromium.org/issues/40244242
> 
>   - review: https://chromium-review.googlesource.com/c/chromium/src/+/5060558
> 
>   - roadmap: https://chromestatus.com/feature/5848709993857024
> 
> 
> 
> The previously-mentioned https://github.com/whatwg/websockets/pull/45 has relevant links to track the implementations. 

 _Originally posted by @qguv in [#20](https://github.com/whatwg/websockets/issues/20#issuecomment-2011908591)_
