### ISSUE TITLE
display a static image in preview if streamer is not running

### ISSUE THREAD

**Issue by gtxaspec** [themactep/thingino-firmware#306]
signal to user streamer is offline.

**Comment by themactep** [comment]
a static image of what exactly? a dead streamer?

**Comment by gtxaspec** [comment]
this is what we see right now if the streamer is down:

![image](https://github.com/user-attachments/assets/b70c353c-64a7-4763-b522-9b4332809f1b)


maybe an image of a camera offline-ish logo? something to indicate of the status...
would be nice to have the same one if the stream is disabled too.

**Comment by gtxaspec** [comment]
kind of like (from chatgpt lol)
![image](https://github.com/user-attachments/assets/3eb41929-5711-424b-a73b-66754d28d829)

**Comment by themactep** [comment]
We can do better :)

![Screenshot-1731042001](https://github.com/user-attachments/assets/776a9a92-5390-4544-ac3b-5c2b3d366540)

**Comment by gtxaspec** [comment]
lol!!! epic.

**Comment by gtxaspec** [comment]
added, thanks @themactep !
