### ISSUE TITLE
/sbin/playonspeaker referencing wrong common file?

### ISSUE THREAD

**Issue by goatzillax** [themactep/thingino-firmware#327]
Should playonspeaker pull in /sbin/common-plugins?

**Comment by themactep** [comment]
oh, we need to just drop that shit altogether. it's a fossil from another life.

**Comment by goatzillax** [comment]
Actually I have been using it to play a local sound file with motion.  It might still be a useful example either playing a local file directly or by fetching a sound file and feeding it to iac.
