### ISSUE TITLE
RTSP Url missing the Port/Channel #7

### ISSUE THREAD

**Issue by rechena** [themactep/thingino-firmware#336]
On the page RTSP/ONVIF Access page the url is:

```
RTSP Mainstream URL
rtsp://thingino:thingino@xxx.xxx.xxx.xxx/
RTSP Substream URL
rtsp://thingino:thingino@xxx.xxx.xxx.xx/
```

But its missing the port and the channels /ch0 or /ch1 in front of the url as pointed in the Preview page.

`rtsp://thingino:[thingino@xxx.xxx.xxx.xxx](mailto:thingino@xxx.xxx.xxx.xxx):554/ch0`

**Comment by themactep** [comment]
fixed in [fe04cd5827b199b716b9cb39b37fd0dbe28baa9a]
