### ISSUE TITLE
add i2c buses to thingino-kopt configs

### ISSUE THREAD

**Issue by gtxaspec** [themactep/thingino-firmware#340]
some units have devices on i2c bus 1.

**Comment by felipecrs** [comment]
I found this in my Howell QJ05T stock bootlog:

```
i2c-gpio i2c-gpio.1: using pins 57 (SDA) and 58 (SCL)
 (null): set:249  hold:250 dev=100000000 h=500 l=500
```

Is this issue related? I wonder what kind of feature is using this i2c.

**Comment by gtxaspec** [comment]
Some devices include additional accessories on the second I2C bus, such as flash memory chips, RTC chips, etc. 

I've found many devices have this second bus enabled with nothing attached to it.  

Looking at the photos of your device, I don't see any such hardware, but it could be there under the lens, etc.
