### ISSUE TITLE
failed update

### ISSUE THREAD

**Issue by cirrusflyer** [themactep/thingino-firmware#348]
Had thingino installed on a Wyze v3 camera, but it was fairly old.  Followed steps here to upgrade including the https://github.com/themactep/thingino-firmware/wiki/Updating-Firmware:

curl -sL -o /sbin/sysupgrade https://raw.githubusercontent.com/themactep/thingino-firmware/refs/heads/master/overlay/lower/usr/sbin/sysupgrade && chmod +x /sbin/sysupgrade then run sysupgrade -p as usual.

It seemed to be going fine, but at one step it lost SSH connection.  After, it just boots up with solid blue light.  Any recovery possible?  Hard reset does nothing.

**Comment by themactep** [comment]
if you lost connection doing upgrade in shell and it the upgrade did not finish, you most likely has a brick on hands. first try to revive it with a fresh firmware on an sd card renamed to `autoupdate-full.bin`, if it does not work then use cloner. please check wiki for details, and ask help in either discord or telegram, not in issues. thank you.
