### ISSUE TITLE
Thingino integration with Wisenet Wave VMS

### ISSUE THREAD

**Issue by shamlord** [themactep/thingino-firmware#354]
5 DEC 2024 firmware. 
Camera: Wyze v3 T31AL

Most audio formats supplied by Thingino appear to not be supported by Wisenet WAVE VMS.
- PCM format from Thingino is 16 bit Big Endian, VMS only supports Mu-Law or A-Law.
- G726 is supported by both Thingino and Wave VMS, but when Thingino is configured to this codec, the VMS reports the camera has no audio sources available.
- Wave VMS shows that the camera supports 2 way audio, but any audio sent to the camera is not played through the camera speaker.

Some background, possibly also helpful:
Wave VMS is available as a free download after a registration form. The software includes a 30 day, 4 camera license for trial use.
The VMS itself has no license fee, sales are done entirely through camera licenses.
Its expensive (~$100 per camera) but easy to use and offers a mobile app with UDP hole punching that is extremely user friendly for my family.
No professional / semi professional ONVIF or RTSP camera available matches the compact size or versatility of these small Ingenic cameras.

**Comment by tERB00** [comment]
Uggghhhh... $100 license for a $30 camera? Isn't it a bit over the top?
If it's about convenience and ease of use - get a recommended $15 NVR, stick it to the back or your family room TV an even your granny will be able to use it! It has mobile app too.
https://github.com/themactep/thingino-firmware/wiki/Integration:-$15-NVR

**Comment by themactep** [comment]
that's an issue for wisenet repo is they have one.

**Comment by shamlord** [comment]
> Uggghhhh... $100 license for a $30 camera? Isn't it a bit over the top? If it's about convenience and ease of use - get a recommended $15 NVR, stick it to the back of your family room's TV an even your granny will be able to use it! It has mobile app too. https://github.com/themactep/thingino-firmware/wiki/Integration:-$15-NVR

Strange, you link to a page about a $15 NVR which does not mention anything regarding a remote access app. Is that remote access app _actually_ easy to use? Coming from Blue Iris, their idea of "easy to use" is insane. Additionally, _how_ the remote app connection is brokered is important. Who controls the server that handshakes that connection? 

The software on the NVR is also important. The "firmware analysis" for that NVR is concerning:
> It tries pretty hard to phone home, even before system setup.
Yeah, no thanks.

**Comment by shamlord** [comment]
> that's an issue for wisenet repo is they have one.

You know they don't have one. Besides, they have a camera and video encoder compatibility list with 21,725 devices from 1,064 manufacturers. Their compatibility with ONVIF and RTSP devices is well sorted. But sure, close the issue because reasons.

**Comment by themactep** [comment]
You want the issue resolved, send a patch.

**Comment by gtxaspec** [comment]
does this run on a PC or dedicated hardware?

**Comment by shamlord** [comment]
> You want the issue resolved, send a patch.

Everyone wants issues resolved. Flippant comments, not so much. I merely reported an issue. That report comes with **no** entitlement on my part. I suspect this problem isn't limited to just the VMS I'm using. The software cost to _me_ on the other hand seems to be an issue for some of you. 

Fix it or don't. But don't expect people to respond positively to comments like those above.

**Comment by shamlord** [comment]
> does this run on a PC or dedicated hardware?

This issue is closed anyway, but since you asked:

The VMS I'm using runs on Windows and Linux. I'm specifically using it on Ubuntu Server, the recommended Linux distribution. Their documentation includes instructions for 20.04 LTS, I am using 24.04.1 LTS. I have had no audio issues with the Wyze cameras not yet converted to Thingino. I also have two Reolink cameras that function without issue.
