### ISSUE TITLE
`sysupgrade -`

### ISSUE THREAD

**Issue by felipecrs** [themactep/thingino-firmware#363]
Guys, this is a really stupid feature but would come in handy. I may implement it myself unless you object to it.

It would make this:

```console
$ scp -O thingino.bin root@192.168.1.31:/tmp/
$ ssh root@192.168.1.31 sysupgrade /tmp/thingino.bin
```

Or this:

```console
$ cat thingino.bin | ssh root@192.168.1.31 tee /tmp/thingino.bin >/dev/null
$ ssh root@192.168.1.31 sysupgrade /tmp/thingino.bin
```

Be simplified to just:

```console
$ cat thingino.bin | ssh root@192.168.1.31 sysupgrade -
```

So, any objections?

**Comment by gtxaspec** [comment]
we have a script in the repo for this, check `scripts/fw_ota.sh`

**Comment by felipecrs** [comment]
That script's awesome. The only downside is that the script would need to be downloaded prior to using. But I think it's worth the price, especially considering it also does a checksum check, which I think is very important.
