### ISSUE TITLE
RTSP urls on rtsp settings page showing incorrectly with double quotes surrounding channel name

### ISSUE THREAD

**Issue by savingprivatebryan** [themactep/thingino-firmware#376]
Small issue, the Mainstream and Substream urls on the RTSP/ONVIF Access settings page in the web ui has double quotes in the channel name but the actual endpoints don't have the double quotes. 
e.g. it shows rtsp://thingino:thingino@192.168.1.45:554/"ch0" which doesn't work unless you remove the double quotes.

![image](https://github.com/user-attachments/assets/8b5c515d-cac2-4008-909a-33891ac69125)

This was using wyze_c3_t31al_atbm

**Comment by gtxaspec** [comment]
is this still an issue in the latest builds?

**Comment by Quadpilotman** [comment]
This also occurs on the wuuk Y0510 just on the substream URL

**Comment by themactep** [comment]
fixed in https://github.com/themactep/thingino-firmware/commit/baf2b561a1245d2fb6fa0d98022c79975738e59b
