### ISSUE TITLE
Debug information loads on all pages

### ISSUE THREAD

**Issue by duhow** [themactep/thingino-firmware#394]
While I understand the purpose of debug, this way will load the debug info from the commands and files into web code, regardless of we want to load it or not.

https://github.com/themactep/thingino-firmware/blob/8ebb8b2fb6d6d6f27a7a24af7b19b42114f04510/package/thingino-webui/files/var/www/x/_footer.cgi#L30

Would it make sense to load with ajax,. or with a query param `url.cgi?debug` or similar?

**Comment by themactep** [comment]
This is an actively developing firmware and debug information is vital at this stage. It does not hurt anyone and does not affect UX in any way. Not a bug.
