### ISSUE TITLE
webui - disable homing always on

### ISSUE THREAD

**Issue by gtxaspec** [themactep/thingino-firmware#396]
steps to reproduce:

fresh build:
turn disable homing slider on
click save
refresh
turn disable homing slider off
click save

slider is always on
clicking DEBUG icon, webui env shows:
`disable_homing: true`
while `fw_printenv -n disable_homing` shows:
```
# fw_printenv -n disable_homing
false
```

issue persists after reboot.

**Comment by themactep** [comment]
![image](https://github.com/user-attachments/assets/1075c884-5157-45ab-83cd-bb416f772eca)

`get` was replaces with `fw_printenv` yesterday but somehow there is still old code in the file.
@CazYokoyama also reported about the new build which did not incude the latest changes.

**Comment by themactep** [comment]
not an issue anymore with the proper code.
