### ISSUE TITLE
wrong snapshot image

### ISSUE THREAD

**Issue by kohalmi666** [themactep/thingino-firmware#55]
image falls apart if /tmp/snapshot.jpg is overwritten at the wrong moment. this picture read at the wrong moment. so it cannot be used for timelapse video. There are a lot of wrong pictures.
you have to use a different method to take the snapshot.

![veroce_parkolo_20240422_1713797019](https://github.com/themactep/thingino-firmware/assets/266651/971f69ec-336b-4518-b29d-d93b5233a1fc)

**Comment by gtxaspec** [comment]
ive attached a test version of the prudynt streamer, are you able to test and see if the issues are resolved?
[prudynt.zip](https://github.com/themactep/thingino-firmware/files/15065256/prudynt.zip)

**Comment by kohalmi666** [comment]
looks good. I downloaded 200 images and all 200 were good. thx

**Comment by gtxaspec** [comment]
great, i'll push the fix to the repo.  thanks!

**Comment by gtxaspec** [comment]
https://github.com/gtxaspec/prudynt-t/commit/4bf39f2038b14907ca45262a1643fd73cbf1e20a
