### ISSUE TITLE
Pink color in streams

### ISSUE THREAD

**Issue by zack-lau** [themactep/thingino-firmware#87]
Hi there, after upgarding the firmware to the 20240525 build on the Wyze Cam 3 (T31X + RTL). The streams (both web preview and RTSP) started to appear pinkish. Just wondering is there any configuration I can tweak to adjust the color settings.

**Comment by johndoewashere2** [comment]
Sounds like the IR cut filter not engaged, can you see if you can toggle the IR cut via the web UI?

**Comment by gtxaspec** [comment]
the ircut logic was refactored recently, swap the gpios
run this command:

`fw_setenv gpio_ircut=52 53`
and reboot

**Comment by zack-lau** [comment]
I can confirm toggling gpio 52 can fix the issue. The solution from gtxaspec fixed the issue permanently.
